import { Review } from "@/app/(app)/review/review-context";

export const reviewData: Review[] = [
  {
	id: "1",
	type: "Model",
	title: "GPT-4 Review",
	rating: 5,
	description: "I love cheese and this model is great for generating text about cheese.",
	date: "2023-10-01",
	ign: "Komiyz",
	role: "Plugin Developer",
  },
  {
	id: "2",
	type: "GUI",
	title: "ChatGPT GUI Review",
	rating: 4,
	description: "I hate cheese but this GUI is user-friendly and intuitive.",
	date: "2023-10-02",
	ign: "aabbiiee",
	role: "Freelancer",
  },
  {
	id: "3",
	type: "Config",
	title: "Configuration Review",
	rating: 4,
	description: "Maybe I like cheese, but this configuration tool is very useful for managing settings.",
	date: "2023-10-03",
	ign: "YepJasmine",
	role: "Admin at ExampleMC",
  },
  {
	id: "4",
	type: "Bedrock",
	title: "Bedrock Review",
	rating: 3,
	description: "yapyap yap, this is a decent tool for Bedrock Edition but could use more features.",
	date: "2023-10-04",
	ign: "Komiyz",
	role: "Developer at Example2MC",
  },
  {
	id: "5",
	type: "Model",
	title: "BERT Review",
	rating: 4,
	description: "Models suck, but BERT is an exception. It generates text about cheese very well.",
	date: "2023-10-05",
	ign: "Fl00fybear",
	role: "Owner of Example2MC",
  },
  {
	id: "6",
	type: "GUI",
	title: "BERT GUI Review",
	rating: 4,
	description: "Intuitive interface for BERT configuration, makes it easy to generate text about cheese.",
	date: "2023-10-06",
	ign: "Avivee",
	role: "Content Lead at ExampleMC",
  },
  {
	id: "7",
	type: "Config",
	title: "BERT Configuration Review",
	rating: 4,
	description: "Great configuration tool for BERT, allows for easy customization of text generation settings.",
	date: "2023-10-07",
	ign: "tulipblossom",
	role: "Developer at ExampleMC",
  },
  {
	id: "8",
	type: "Bedrock",
	title: "Bedrock AI Review",
	rating: 3,
	description: "goofy goof, this Bedrock AI tool is okay but needs more cheese-related features.",
	date: "2023-10-08",
	ign: "Amazon",
	role: "Owner of ExampleMC",
  }
];